require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'config/puma.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/NestedGroups:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

Naming/InclusiveLanguage:
  Exclude:
    - 'spec/rails_helper.rb'
