default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_api_rg_development
  username: <%= Rails.application.credentials[:postgresql][:db_user] %>
  password: <%= Rails.application.credentials[:postgresql][:db_password] %>

test:
  <<: *default
  database: todo_api_rg_test
  username: <%= Rails.application.credentials[:postgresql][:db_user] %>
  password: <%= Rails.application.credentials[:postgresql][:db_password] %>
  
